#!/bin/bash
echo "MongoDB Troubleshooting Tool"
echo "--------------------------"
echo "1. Check server status"
echo "   Usage: mongosh --host <host> --eval \"db.serverStatus()\""
echo "2. Check database stats"
echo "   Usage: mongosh --host <host> --eval \"db.stats()\""
echo "3. Check collection stats"
echo "   Usage: mongosh --host <host> --eval \"db.getCollection('<collection>').stats()\""
echo "4. Check current operations"
echo "   Usage: mongosh --host <host> --eval \"db.currentOp()\""
echo "5. Check index usage"
echo "   Usage: mongosh --host <host> --eval \"db.getCollection('<collection>').aggregate([{\$indexStats: {}}])\""
echo "6. Check slow queries"
echo "   Usage: mongosh --host <host> --eval \"db.getSiblingDB('admin').system.profile.find({millis: {\$gt: 100}}).sort({ts: -1}).limit(10).pretty()\""
echo "7. Check connection count"
echo "   Usage: mongosh --host <host> --eval \"db.serverStatus().connections\"" 
