#!/bin/bash
echo "PostgreSQL Troubleshooting Tool"
echo "----------------------------"
echo "1. Check active connections"
echo "   Usage: psql -h <host> -U <user> -c \"SELECT count(*) FROM pg_stat_activity;\""
echo "2. Check database sizes"
echo "   Usage: psql -h <host> -U <user> -c \"SELECT pg_database.datname, pg_size_pretty(pg_database_size(pg_database.datname)) AS size FROM pg_database ORDER BY pg_database_size(pg_database.datname) DESC;\""
echo "3. Check table sizes"
echo "   Usage: psql -h <host> -U <user> -d <dbname> -c \"SELECT relname, pg_size_pretty(pg_total_relation_size(relid)) AS total_size FROM pg_catalog.pg_statio_user_tables ORDER BY pg_total_relation_size(relid) DESC;\""
echo "4. Check index usage"
echo "   Usage: psql -h <host> -U <user> -d <dbname> -c \"SELECT relname, indexrelname, idx_scan FROM pg_stat_user_indexes ORDER BY idx_scan DESC;\""
echo "5. Check query performance"
echo "   Usage: psql -h <host> -U <user> -d <dbname> -c \"SELECT query, calls, total_time, rows, shared_blks_hit FROM pg_stat_statements ORDER BY total_time DESC LIMIT 10;\""
echo "6. Check for locks"
echo "   Usage: psql -h <host> -U <user> -d <dbname> -c \"SELECT blocked_locks.pid AS blocked_pid, blocked_activity.usename AS blocked_user, blocking_locks.pid AS blocking_pid, blocking_activity.usename AS blocking_user, blocked_activity.query AS blocked_statement, blocking_activity.query AS blocking_statement FROM pg_catalog.pg_locks blocked_locks JOIN pg_catalog.pg_stat_activity blocked_activity ON blocked_activity.pid = blocked_locks.pid JOIN pg_catalog.pg_locks blocking_locks ON blocking_locks.locktype = blocked_locks.locktype AND blocking_locks.database IS NOT DISTINCT FROM blocked_locks.database AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid AND blocking_locks.pid != blocked_locks.pid JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid WHERE NOT blocked_locks.granted;\"" 
