name: Build and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: 'Container Name'
        required: true
      tag_name:
        description: 'Tag Name'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.SARVENT_DOCKERHUB_USERNAME }}
        password: ${{ secrets.SARVENT_DOCKERHUB_ACCESS_TOKEN }}

    - name: Check for base image update
      id: check_base_image
      run: |
        echo "::set-output name=updated::$(docker pull bitnami/wordpress:${{ github.event.inputs.tag_name }} | grep -q 'Image is up to date' && echo 'false' || echo 'true')"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      if: steps.check_base_image.outputs.updated == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ./${{ github.event.inputs.container_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: sarvent/${{ github.event.inputs.container_name }}:${{ github.event.inputs.tag_name }}
        build-args: |
          TAG_NAME=${{ github.event.inputs.tag_name }}
